<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="manjula-VAIO" name="com.testpackage.Timeout" tests="1" failures="0" timestamp="15 Feb 2019 03:04:07 GMT" time="5.038" errors="1">
  <testcase name="infiniteLoop" time="5.038" classname="com.testpackage.Timeout">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.testpackage.Timeout.infiniteLoop() didn&#039;t finish within the time-out 5000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testpackage.Timeout.infiniteLoop() didn't finish within the time-out 5000
]]>
    </error>
  </testcase> <!-- infiniteLoop -->
</testsuite> <!-- com.testpackage.Timeout -->
